# Generated by Django 3.2 on 2021-04-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postslike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postslike',
            old_name='posts',
            new_name='post',
        ),
    ]
