# Generated by Django 3.2 on 2021-04-12 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_rename_posts_postslike_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostsLike',
            new_name='PostLike',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_username', through='posts.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
