# Generated by Django 3.2 on 2021-04-12 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210412_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='postlikes', through='posts.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
